version: 2
jobs:
  npm_install:
    docker:
      - image: circleci/node:8.16-stretch
    working_directory: ~/build
    steps:
      - checkout
      - attach_workspace:
           at: ~/build
      - restore_cache:
          keys:
            - node-dependencies-{{ checksum "package.json" }}
            - node-dependencies-
      - run: npm install
      - persist_to_workspace:
          root: .
          paths: node_modules
      - save_cache:
          key: node-dependencies{{ checksum "package.json" }}
          paths:
            - node_modules

  lint:
    working_directory: ~/build
    docker:
      - image: circleci/node:6.14-stretch
    steps:
      - checkout
      - attach_workspace:
          at: ~/build
      - run:
          command: ./node_modules/.bin/eslint --format junit -o ./coverage/eslint/results.xml .
          when: always
      - store_test_results:
          path: coverage
      - run: ./node_modules/.bin/pjv -w -r

workflows:
  version: 2
  build_and_test:
    jobs:
      - npm_install
      - lint:
          requires:
            - npm_install
